baseurl = "http://www.huifang.nl/"
languageCode = "zh-CN"
title = "FILOU & HUIFANG"
theme = "hugo-theme-minos"

paginate = 5 

[params]
googleAnalytics = "UA-103272114-1"

disqusShortname = "huifang"

[permalinks]
    post = "/:year/:month/:day/:slug/"

[[menu.main]]
    name = "关于"
    url = "/about/"
    

    
